apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: realworld
type: Opaque
stringData:
  DATABASE_URL: postgresql://conduit:k8sConduitPass123@postgres:5432/conduit
  JWT_SECRET: k8sJwtSecretChangeMe
