apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nevenadimova-sys/realworld.git
    targetRevision: main
    path: app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: realworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
