apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: realworld
type: Opaque
stringData:
  DATABASE_URL: postgresql://conduit:CHANGE_ME@postgres:5432/conduit
  JWT_SECRET: CHANGE_ME
